     Running `target/x86_64-unknown-linux-gnu/debug/stylus-arenaton`
/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IOwnable  {
    function owner() external view returns (address);

    function transferOwnership(address new_owner) external;

    error OwnableUnauthorizedAccount(address);

    error OwnableInvalidOwner(address);
}

interface IAccessControl  {
    function hasRole(bytes32 role, address account) external view returns (bool);

    function onlyRole(bytes32 role) external view;

    function getRoleAdmin(bytes32 role) external view returns (bytes32);

    function grantArenatonRole(address account) external;

    function revokeArenatonRole(address account) external;

    error AccessControlUnauthorizedAccount(address, bytes32);

    error AccessControlBadConfirmation();
}

interface IArenatonEngine is IOwnable, IAccessControl  {
    function addEvent(string calldata event_id, uint256 start_date, uint8 sport) external returns (bool);

    function stakeAton(string calldata _event_id, uint256 _amount_aton, uint8 _team) external returns (bool);

    function stakeEth(string calldata _event_id, uint8 _team) external returns (bool);

    function closeEvent(string calldata _event_id, uint8 _winner) external returns (bool);

    function payEvent(string calldata _event_id, uint128 _batch_size) external returns (bool);

    function getEvent(string calldata _event_id) external view returns (bool);

    function getEventList() external view returns (bool);

    function getPlayerEventList(address _player) external view returns (bool);

    error ZeroEther(address);

    error ZeroAton(address);

    error AlreadyInitialized();
}