/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IStakeEngine  {
    function initialize(address _aton_address, address _core_address) external returns (bool);

    function readEventCore(string calldata _event_id) external returns (uint64, uint8, uint8);

    function stake(string calldata _event_id, uint256 _amount, uint8 _team) external payable returns (bool);

    function getStakes(string calldata _event_id, uint64 page_size) external view returns (uint256,uint8,uint64)[] memory;

    function payEvent(string calldata event_id, address player_address) external returns (bool);

    function getPlayerEvents(uint64 page_size) external view returns (string,uint64,uint8,uint256,uint256,uint8)[] memory;

    error ErrorCode();
}