/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IVault  {
    function atonAddress() external view returns (address);

    function initialize(address _aton_address) external returns (bool);

    function accumulateAton(uint256 amount) external returns (bool);

    function summary(address player) external view returns (uint256, uint256, uint256, uint256, uint256);

    function playerCommission(address player) external view returns (uint256);

    function clearCommission(address player) external;

    error Zero(address);

    error UnauthorizedAccount(address);
}